name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
<<<<<<< HEAD
    branches: [ master ]
=======
    branches: [ main ]

>>>>>>> aabdd74acf80554688364bc21dce443096c6dc6e
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
    # - name: Run tests
      # run: swift test -v
